package render

import (
	"bytes"
	"fmt"
	"io"
	"maps"
	"slices"

	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/magodo/tfproviderdocs/internal/metadata"
)

type Example struct {
	Header      string
	Description string
	HCL         []byte
}

type ResourceRender struct {
	ProviderName string
	ResourceType string
	Schema       metadata.ResourceSchema

	Subcategory string
	Examples    []Example

	// TODO
	// IdentitySchemaInfo string
	// ImportId           string
}

func (render ResourceRender) Render(w io.Writer) error {
	if err := render.renderHeader(w); err != nil {
		return err
	}

	io.WriteString(w, "\n")
	if err := render.renderDescription(w); err != nil {
		return err
	}

	if len(render.Examples) != 0 {
		io.WriteString(w, "\n")
		if err := render.renderExample(w); err != nil {
			return err
		}
	}

	io.WriteString(w, "\n")
	if err := render.renderSchema(w); err != nil {
		return err
	}

	// TODO: Render Import

	return nil
}

func (render ResourceRender) renderHeader(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `---
# generated by https://github.com/magodo/tfproviderdocs
page_title: "%[1]s Resource - %[2]s"
subcategory: "%[3]s"
description: |-
  %[4]s
---
`, render.ResourceType, render.ProviderName, render.Subcategory, render.Schema.Description); err != nil {
		return err
	}
	return nil
}

func (render ResourceRender) renderDescription(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `# %s (Resource)
`, render.ResourceType); err != nil {
		return err
	}

	if deprecation := render.Schema.Deprecation; deprecation != "" {
		if _, err := fmt.Fprintf(w, `
!> %s
`, deprecation); err != nil {
			return nil
		}
	}

	if _, err := fmt.Fprintf(w, `
%s
`, render.Schema.Description); err != nil {
		return err
	}

	return nil
}

func (render ResourceRender) renderExample(w io.Writer) error {
	if examples := render.Examples; len(examples) != 0 {
		if _, err := io.WriteString(w, "## Example Usage\n"); err != nil {
			return err
		}
		for _, example := range examples {
			if example.Header != "" {
				if _, err := fmt.Fprintf(w, "\n### %s\n", example.Header); err != nil {
					return err
				}
			}
			if example.Description != "" {
				if _, err := fmt.Fprintf(w, "\n%s\n", example.Description); err != nil {
					return err
				}
			}
			if _, err := fmt.Fprintf(w, "\n```hcl\n%s\n```\n", bytes.TrimSpace(hclwrite.Format(example.HCL))); err != nil {
				return err
			}
		}
	}
	return nil
}

func (render ResourceRender) renderSchema(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `## Schema
`); err != nil {
		return err
	}

	sections := []struct {
		name   string
		fields []metadata.Field
	}{
		{
			name:   "Required",
			fields: render.Schema.Fields.RequiredFields(),
		},
		{
			name:   "Optional",
			fields: render.Schema.Fields.OptionalFields(),
		},
		{
			name:   "Read-Only",
			fields: render.Schema.Fields.ComputedFields(),
		},
	}

	for _, section := range sections {
		if len(section.fields) == 0 {
			continue
		}
		if _, err := fmt.Fprintf(w, `
### %s
	
`, section.name); err != nil {
			return err
		}

		for _, field := range section.fields {
			if err := render.renderField(w, field); err != nil {
				return err
			}
		}
	}

	if nested := render.Schema.Nested; len(nested) != 0 {
		io.WriteString(w, "\n")
		if err := render.renderNestedFields(w, nested); err != nil {
			return err
		}
	}

	return nil
}

func (render ResourceRender) renderNestedFields(w io.Writer, fields metadata.NestedFields) error {
	keys := slices.Collect(maps.Keys(fields))
	slices.Sort(keys)
	for _, key := range keys {
		field := fields[key]

		if _, err := fmt.Fprintf(w, `<a id="nested--%[1]s"></a>
### Nested Schema for %[2]s%[1]s%[2]s
`, key, "`"); err != nil {
			return err
		}

		if l := field.Validators; len(l) != 0 {
			io.WriteString(w, "\nValidators:\n\n")
			for _, e := range l {
				if _, err := fmt.Fprintf(w, "- %s\n", e); err != nil {
					return err
				}
			}
		}

		sections := []struct {
			name   string
			fields []metadata.Field
		}{
			{
				name:   "Required",
				fields: field.Fields.RequiredFields(),
			},
			{
				name:   "Optional",
				fields: field.Fields.OptionalFields(),
			},
			{
				name:   "Read-Only",
				fields: field.Fields.ComputedFields(),
			},
		}

		for _, section := range sections {
			if len(section.fields) == 0 {
				continue
			}
			if _, err := fmt.Fprintf(w, `
%s:

`, section.name); err != nil {
				return err
			}

			for _, field := range section.fields {
				if err := render.renderField(w, field); err != nil {
					return err
				}
			}
		}
	}

	return nil
}

func (render ResourceRender) renderField(w io.Writer, field metadata.Field) error {
	if _, err := fmt.Fprintf(w, "- `%s` (%s) %s", field.Name, field.Traits(), field.Description); err != nil {
		return err
	}
	if v := field.Default(); v != "" {
		fmt.Fprintf(w, " %s", v)
	}
	if field.NestedLink() != "" {
		fmt.Fprintf(w, " %s", field.NestedLink())
	}
	io.WriteString(w, "\n")

	if l := field.PlanModifiers(); len(l) != 0 {
		io.WriteString(w, "\n\tPlan Modifiers:\n\n")
		for _, e := range l {
			if _, err := fmt.Fprintf(w, "\t- %s\n", e); err != nil {
				return err
			}
		}
	}

	if l := field.Validators(); len(l) != 0 {
		io.WriteString(w, "\n\tValidators:\n\n")
		for _, e := range l {
			if _, err := fmt.Fprintf(w, "\t- %s\n", e); err != nil {
				return err
			}
		}
	}

	if field.Deprecation != "" {
		if _, err := fmt.Fprintf(w, "\n\t!> %s\n", field.Deprecation); err != nil {
			return err
		}
	}

	return nil
}
