package metadata

import (
	"fmt"
	"io"
	"maps"
	"slices"
)

type providerRenderBuilder struct {
	ProviderName string
	Schema       ProviderSchema
	Examples     []Example
}

func (b providerRenderBuilder) renderHeader(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `---
# generated by https://github.com/magodo/tfproviderdocs
page_title: "%[1]s Provider"
description: |-
  %[2]s
---
`, b.ProviderName, b.Schema.Description); err != nil {
		return err
	}
	return nil
}

func (b providerRenderBuilder) renderDescription(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `# %s Provider
`, b.ProviderName); err != nil {
		return err
	}

	if deprecation := b.Schema.Deprecation; deprecation != "" {
		if _, err := fmt.Fprintf(w, `
!> %s
`, deprecation); err != nil {
			return nil
		}
	}

	if _, err := fmt.Fprintf(w, `
%s
`, b.Schema.Description); err != nil {
		return err
	}

	return nil
}

func (b providerRenderBuilder) renderExample(w io.Writer) error {
	return renderExamples(w, b.Examples)
}

func (b providerRenderBuilder) renderSchema(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `## Schema
`); err != nil {
		return err
	}

	sections := []struct {
		name   string
		fields []ProviderField
	}{
		{
			name:   "Required",
			fields: b.Schema.Fields.RequiredFields(),
		},
		{
			name:   "Optional",
			fields: b.Schema.Fields.OptionalFields(),
		},
	}

	for _, section := range sections {
		if len(section.fields) == 0 {
			continue
		}
		if _, err := fmt.Fprintf(w, `
### %s
	
`, section.name); err != nil {
			return err
		}

		for _, field := range section.fields {
			if err := b.renderField(w, field); err != nil {
				return err
			}
		}
	}

	if nested := b.Schema.Nested; len(nested) != 0 {
		io.WriteString(w, "\n")
		if err := b.renderNestedFields(w, nested); err != nil {
			return err
		}
	}

	return nil
}

func (b providerRenderBuilder) renderNestedFields(w io.Writer, fields ProviderNestedFields) error {
	keys := slices.Collect(maps.Keys(fields))
	slices.Sort(keys)
	for _, key := range keys {
		field := fields[key]

		if _, err := fmt.Fprintf(w, `<a id="nested--%[1]s"></a>
### Nested Schema for %[2]s%[1]s%[2]s
`, key, "`"); err != nil {
			return err
		}

		if l := field.Validators; len(l) != 0 {
			io.WriteString(w, "\nValidators:\n\n")
			for _, e := range l {
				if _, err := fmt.Fprintf(w, "- %s\n", e); err != nil {
					return err
				}
			}
		}

		sections := []struct {
			name   string
			fields []ProviderField
		}{
			{
				name:   "Required",
				fields: field.Fields.RequiredFields(),
			},
			{
				name:   "Optional",
				fields: field.Fields.OptionalFields(),
			},
		}

		for _, section := range sections {
			if len(section.fields) == 0 {
				continue
			}
			if _, err := fmt.Fprintf(w, `
%s:

`, section.name); err != nil {
				return err
			}

			for _, field := range section.fields {
				if err := b.renderField(w, field); err != nil {
					return err
				}
			}
		}
	}

	return nil
}

func (b providerRenderBuilder) renderField(w io.Writer, field ProviderField) error {
	if _, err := fmt.Fprintf(w, "- `%s` (%s) %s", field.Name, field.Traits(), field.Description); err != nil {
		return err
	}
	if field.NestedLink() != "" {
		fmt.Fprintf(w, " %s", field.NestedLink())
	}
	io.WriteString(w, "\n")

	if l := field.Validators(); len(l) != 0 {
		io.WriteString(w, "\n\tValidators:\n\n")
		for _, e := range l {
			if _, err := fmt.Fprintf(w, "\t- %s\n", e); err != nil {
				return err
			}
		}
	}

	if field.Deprecation != "" {
		if _, err := fmt.Fprintf(w, "\n\t!> %s\n", field.Deprecation); err != nil {
			return err
		}
	}

	return nil
}
