package metadata

import (
	"fmt"
	"io"
	"maps"
	"slices"
)

type ephemeralRenderBuilder struct {
	ProviderName string
	ResourceType string

	Metadata EphemeralMetadata

	Subcategory string
	Examples    []Example
}

func (b ephemeralRenderBuilder) renderHeader(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `---
# generated by https://github.com/magodo/tfproviderdocs
page_title: "%[1]s Ephemeral Resource - %[2]s"
subcategory: "%[3]s"
description: |-
  %[4]s
---
`, b.ResourceType, b.ProviderName, b.Subcategory, b.Metadata.Schema.Description); err != nil {
		return err
	}
	return nil
}

func (b ephemeralRenderBuilder) renderDescription(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `# %s (Ephemeral Resource)
`, b.ResourceType); err != nil {
		return err
	}

	if deprecation := b.Metadata.Schema.Deprecation; deprecation != "" {
		if _, err := fmt.Fprintf(w, `
!> %s
`, deprecation); err != nil {
			return nil
		}
	}

	if _, err := fmt.Fprintf(w, `
%s
`, b.Metadata.Schema.Description); err != nil {
		return err
	}

	return nil
}

func (b ephemeralRenderBuilder) renderExample(w io.Writer) error {
	return renderExamples(w, b.Examples)
}

func (b ephemeralRenderBuilder) renderSchema(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `## Schema
`); err != nil {
		return err
	}

	sections := []struct {
		name   string
		fields []EphemeralField
	}{
		{
			name:   "Required",
			fields: b.Metadata.Schema.Fields.RequiredFields(),
		},
		{
			name:   "Optional",
			fields: b.Metadata.Schema.Fields.OptionalFields(),
		},
		{
			name:   "Read-Only",
			fields: b.Metadata.Schema.Fields.ComputedFields(),
		},
	}

	for _, section := range sections {
		if len(section.fields) == 0 {
			continue
		}
		if _, err := fmt.Fprintf(w, `
### %s
	
`, section.name); err != nil {
			return err
		}

		for _, field := range section.fields {
			if err := b.renderField(w, field); err != nil {
				return err
			}
		}
	}

	if nested := b.Metadata.Schema.Nested; len(nested) != 0 {
		io.WriteString(w, "\n")
		if err := b.renderNestedFields(w, nested); err != nil {
			return err
		}
	}

	return nil
}

func (b ephemeralRenderBuilder) renderNestedFields(w io.Writer, fields EphemeralNestedFields) error {
	keys := slices.Collect(maps.Keys(fields))
	slices.Sort(keys)
	for _, key := range keys {
		field := fields[key]

		if _, err := fmt.Fprintf(w, `<a id="nested--%[1]s"></a>
### Nested Schema for %[2]s%[1]s%[2]s
`, key, "`"); err != nil {
			return err
		}

		if l := field.Validators; len(l) != 0 {
			io.WriteString(w, "\nValidators:\n\n")
			for _, e := range l {
				if _, err := fmt.Fprintf(w, "- %s\n", e); err != nil {
					return err
				}
			}
		}

		sections := []struct {
			name   string
			fields []EphemeralField
		}{
			{
				name:   "Required",
				fields: field.Fields.RequiredFields(),
			},
			{
				name:   "Optional",
				fields: field.Fields.OptionalFields(),
			},
			{
				name:   "Read-Only",
				fields: field.Fields.ComputedFields(),
			},
		}

		for _, section := range sections {
			if len(section.fields) == 0 {
				continue
			}
			if _, err := fmt.Fprintf(w, `
%s:

`, section.name); err != nil {
				return err
			}

			for _, field := range section.fields {
				if err := b.renderField(w, field); err != nil {
					return err
				}
			}
		}
	}

	return nil
}

func (b ephemeralRenderBuilder) renderField(w io.Writer, field EphemeralField) error {
	if _, err := fmt.Fprintf(w, "- `%s` (%s) %s", field.Name, field.Traits(), field.Description); err != nil {
		return err
	}
	if field.NestedLink() != "" {
		fmt.Fprintf(w, " %s", field.NestedLink())
	}
	io.WriteString(w, "\n")

	if l := field.Validators(); len(l) != 0 {
		io.WriteString(w, "\n\tValidators:\n\n")
		for _, e := range l {
			if _, err := fmt.Fprintf(w, "\t- %s\n", e); err != nil {
				return err
			}
		}
	}

	if field.Deprecation != "" {
		if _, err := fmt.Fprintf(w, "\n\t!> %s\n", field.Deprecation); err != nil {
			return err
		}
	}

	return nil
}
