package metadata

import (
	"bytes"
	"fmt"
	"io"
	"maps"
	"slices"

	"github.com/hashicorp/hcl/v2/hclwrite"
)

type resourceRenderBuilder struct {
	ProviderName string
	ResourceType string

	Metadata ResourceMetadata

	Subcategory string
	Examples    []Example

	// Import
	ImportId         *ImportId
	IdentityExamples []Example
}

func (b resourceRenderBuilder) renderHeader(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `---
# generated by https://github.com/magodo/tfproviderdocs
page_title: "%[1]s Resource - %[2]s"
subcategory: "%[3]s"
description: |-
  %[4]s
---
`, b.ResourceType, b.ProviderName, b.Subcategory, b.Metadata.Schema.Description); err != nil {
		return err
	}
	return nil
}

func (b resourceRenderBuilder) renderDescription(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `# %s (Resource)
`, b.ResourceType); err != nil {
		return err
	}

	if deprecation := b.Metadata.Schema.Deprecation; deprecation != "" {
		if _, err := fmt.Fprintf(w, `
!> %s
`, deprecation); err != nil {
			return nil
		}
	}

	if _, err := fmt.Fprintf(w, `
%s
`, b.Metadata.Schema.Description); err != nil {
		return err
	}

	return nil
}

func (b resourceRenderBuilder) renderExample(w io.Writer) error {
	if examples := b.Examples; len(examples) != 0 {
		if _, err := io.WriteString(w, "## Example Usage\n"); err != nil {
			return err
		}
		for _, example := range examples {
			if example.Header != nil {
				if _, err := fmt.Fprintf(w, "\n### %s\n", *example.Header); err != nil {
					return err
				}
			}
			if example.Description != nil {
				if _, err := fmt.Fprintf(w, "\n%s\n", *example.Description); err != nil {
					return err
				}
			}
			if example.HCL != nil {
				if _, err := fmt.Fprintf(w, "\n```terraform\n%s\n```\n", bytes.TrimSpace(hclwrite.Format(example.HCL))); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (b resourceRenderBuilder) renderSchema(w io.Writer) error {
	if _, err := fmt.Fprintf(w, `## Schema
`); err != nil {
		return err
	}

	sections := []struct {
		name   string
		fields []ResourceField
	}{
		{
			name:   "Required",
			fields: b.Metadata.Schema.Fields.RequiredFields(),
		},
		{
			name:   "Optional",
			fields: b.Metadata.Schema.Fields.OptionalFields(),
		},
		{
			name:   "Read-Only",
			fields: b.Metadata.Schema.Fields.ComputedFields(),
		},
	}

	for _, section := range sections {
		if len(section.fields) == 0 {
			continue
		}
		if _, err := fmt.Fprintf(w, `
### %s
	
`, section.name); err != nil {
			return err
		}

		for _, field := range section.fields {
			if err := b.renderField(w, field); err != nil {
				return err
			}
		}
	}

	if nested := b.Metadata.Schema.Nested; len(nested) != 0 {
		io.WriteString(w, "\n")
		if err := b.renderNestedFields(w, nested); err != nil {
			return err
		}
	}

	return nil
}

func (b resourceRenderBuilder) renderNestedFields(w io.Writer, fields ResourceNestedFields) error {
	keys := slices.Collect(maps.Keys(fields))
	slices.Sort(keys)
	for _, key := range keys {
		field := fields[key]

		if _, err := fmt.Fprintf(w, `<a id="nested--%[1]s"></a>
### Nested Schema for %[2]s%[1]s%[2]s
`, key, "`"); err != nil {
			return err
		}

		if l := field.Validators; len(l) != 0 {
			io.WriteString(w, "\nValidators:\n\n")
			for _, e := range l {
				if _, err := fmt.Fprintf(w, "- %s\n", e); err != nil {
					return err
				}
			}
		}

		sections := []struct {
			name   string
			fields []ResourceField
		}{
			{
				name:   "Required",
				fields: field.Fields.RequiredFields(),
			},
			{
				name:   "Optional",
				fields: field.Fields.OptionalFields(),
			},
			{
				name:   "Read-Only",
				fields: field.Fields.ComputedFields(),
			},
		}

		for _, section := range sections {
			if len(section.fields) == 0 {
				continue
			}
			if _, err := fmt.Fprintf(w, `
%s:

`, section.name); err != nil {
				return err
			}

			for _, field := range section.fields {
				if err := b.renderField(w, field); err != nil {
					return err
				}
			}
		}
	}

	return nil
}

func (b resourceRenderBuilder) renderField(w io.Writer, field ResourceField) error {
	if _, err := fmt.Fprintf(w, "- `%s` (%s) %s", field.Name, field.Traits(), field.Description); err != nil {
		return err
	}
	if v := field.Default(); v != "" {
		fmt.Fprintf(w, " %s", v)
	}
	if field.NestedLink() != "" {
		fmt.Fprintf(w, " %s", field.NestedLink())
	}
	io.WriteString(w, "\n")

	if l := field.PlanModifiers(); len(l) != 0 {
		io.WriteString(w, "\n\tPlan Modifiers:\n\n")
		for _, e := range l {
			if _, err := fmt.Fprintf(w, "\t- %s\n", e); err != nil {
				return err
			}
		}
	}

	if l := field.Validators(); len(l) != 0 {
		io.WriteString(w, "\n\tValidators:\n\n")
		for _, e := range l {
			if _, err := fmt.Fprintf(w, "\t- %s\n", e); err != nil {
				return err
			}
		}
	}

	if field.Deprecation != "" {
		if _, err := fmt.Fprintf(w, "\n\t!> %s\n", field.Deprecation); err != nil {
			return err
		}
	}

	return nil
}

func (b resourceRenderBuilder) renderImport(w io.Writer) error {
	if identity := b.Metadata.Identity; b.ImportId != nil || identity != nil {
		io.WriteString(w, "## Import\n")

		if b.ImportId != nil {
			io.WriteString(w, "\n")
			if err := b.renderImportId(w, *b.ImportId); err != nil {
				return err
			}
		}

		if identity != nil {
			io.WriteString(w, "\n")
			if err := b.renderImportIdentity(w, *identity); err != nil {
				return err
			}
		}
	}
	return nil
}

func (b resourceRenderBuilder) renderImportId(w io.Writer, importId ImportId) error {
	if _, err := fmt.Fprintf(w, `### Import ID

The [%[1]sterraform import%[1]s command](https://developer.hashicorp.com/terraform/cli/commands/import) can be used with the id format: %[1]s%[2]s%[1]s, for example:

%[1]s%[1]s%[1]sshell
$ terraform import %[3]s.example "%[4]s"
%[1]s%[1]s%[1]s

In Terraform v1.5.0 and later, the [%[1]simport%[1]s block](https://developer.hashicorp.com/terraform/language/block/import) can be used with the %[1]sid%[1]s attribute, for example:

%[1]s%[1]s%[1]sterraform
import {
  to = %[3]s.example
  id = "%[4]s"
}
%[1]s%[1]s%[1]s
`, "`", importId.Format, b.ResourceType, importId.Example); err != nil {
		return err
	}

	return nil
}

func (b resourceRenderBuilder) renderImportIdentity(w io.Writer, schema ResourceIdentitySchema) error {
	formatExample := func(example []byte) []byte {
		return hclwrite.Format(fmt.Appendf(nil, `import {
  to = %s.example
  identity = {
    %s
  }
}`, b.ResourceType, bytes.TrimSpace(example)))
	}

	if _, err := fmt.Fprintf(w, `### Import Identity

In Terraform v1.12.0 and later, the [%[1]simport%[1]s block](https://developer.hashicorp.com/terraform/language/block/import) can be used with the %[1]sidentity%[1]s attribute.
`, "`"); err != nil {
		return err
	}

	for _, example := range b.IdentityExamples {
		if example.Header != nil {
			if _, err := fmt.Fprintf(w, "\n#### Example: %s\n", *example.Header); err != nil {
				return err
			}
		}
		if example.Description != nil {
			if _, err := fmt.Fprintf(w, "\n%s\n", *example.Description); err != nil {
				return err
			}
		}
		if example.HCL != nil {
			if _, err := fmt.Fprintf(w, "\n```terraform\n%s\n```\n", formatExample(example.HCL)); err != nil {
				return err
			}
		}
	}

	sections := []struct {
		name   string
		fields []ResourceIdentityField
	}{
		{
			name:   "Required",
			fields: schema.Fields.RequiredFields(),
		},
		{
			name:   "Optional",
			fields: schema.Fields.OptionalFields(),
		},
	}

	for _, section := range sections {
		if len(section.fields) == 0 {
			continue
		}
		if _, err := fmt.Fprintf(w, `
%s:

`, section.name); err != nil {
			return err
		}

		for _, field := range section.fields {
			if err := b.renderIdentityField(w, field); err != nil {
				return err
			}
		}
	}
	return nil
}

func (b resourceRenderBuilder) renderIdentityField(w io.Writer, field ResourceIdentityField) error {
	if _, err := fmt.Fprintf(w, "- `%s` (%s) %s\n", field.Name, field.Traits(), field.Description); err != nil {
		return err
	}
	return nil
}
